[package]
name = "aes-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
rand = "0.8"
anyhow = "1.0"
zeroize = "1.5"
rpassword = "7.0"
pbkdf2 = "0.11"
hmac = "0.12"
sha2 = "0.10"

